### ISSUE TITLE
Matrix testing

### ISSUE THREAD

**Issue by hadim** [prefix-dev/setup-pixi#48] opened 2023-11-30 14:28 UTC
I am experimenting using pixi and its GH Actions to replace my `micromamba` workflow.

Currently my CI looks like:

```yaml
      - name: Setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: env.yml
          environment-name: my_env
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}
            rdkit=${{ matrix.rdkit-version }}
```

I am wondering whether something similar is possible with `prefix-dev/setup-pixi`?

**Comment by pavelzw** [comment] 2023-11-30 14:33
Duplicate of #11.
I have a workaround for this, see https://github.com/Quantco/polarify/blob/dcc30139873c4aa7500465e116b6f9f6194b77b3/.github/workflows/ci.yml#L19-L40 (notice that this won't be able to use caching since you need to re-solve the environment for each configuration)

Once the upstream issues have been fixed, I can start to integrate it into `setup-pixi`.

**Closed by pavelzw** 2023-11-30 14:33 UTC

**Comment by pavelzw** [comment] 2024-01-30 23:54
This will come with the next `pixi` and `setup-pixi` release, see #70
